### PR TITLE
ppc64le platform support

### PR DESCRIPTION
**Pull request by mtbrandy**

### CODE REVIEW

**Comment by fommil** [comment]
Thanks. We should probably have a property that allows people to define this stuff dynamically.

What is this platform? I've never heard of it

**Comment by mtbrandy** [comment]
ppc64le == PowerPC 64bit Little-Endian.  Additional information available here: http://openpowerfoundation.org/technical/technical-resources/technical-specifications/

Specifically, we are interested in enabling in this project and netlib-java for use in Spark.  I will be submit a PR for netlib-java native libraries next.

**Comment by fommil** [comment]
It's extremely unlikely that I'll make a release of netlib-java for this, so don't hold your breath. I'd need access to the hardware to build and test the target, plus I lose a day peer release due the the complex cross building. Unless your PR is more than just a new target, I'd recommend just creating your own in-house native build.

**Comment by mtbrandy** [comment]
@fommil, thanks for the guidance.  Do you have a CI environment to automate what sounds like a complex build and test process?  I'll do some legwork to see how painless we can make this (cross-compiler, easy HW access) and we'll go from there.

**Comment by fommil** [comment]
no CI unfortunately thanks to lack of good cross compilers for OS X. I could do everything apart from OS X in a docker node in drone.io but to be honest it's not a priority because netlib-java has been incredibly stable. If I was picking up the project to add some major new feature (like complex numbers or bytebuffers, which would need to be funded for several months of hard grunt work) then it'd be the first thing I'd do.

**Comment by fommil** [comment]
btw, building for one target machine shouldn't be **too** onerous. Its the full build that sucks.

**Pull request merged**
